dictionaries = ["en_us"]

words = [
  "nvim",
  "Neovim",
  "bufnr",
  "qflist",
  "toplevel",
  "trimempty",
  "lnum",
  "augroup",
  "nargs",
  "Wipeout",
  "virt",
]

include_paths = [
  "**/*.lua",
  "**/*.md",
]
